const SUPABASE_URL = 'https://wsqekqjnnynlhekdqsmj.supabase.co';
const SUPABASE_KEY = 'sb_publishable_osYlHilUpUSHwvDlN1b3sQ_KkVaQTyu';
const API = SUPABASE_URL + '/rest/v1';
const headers = { apikey: SUPABASE_KEY, Authorization: 'Bearer ' + SUPABASE_KEY, 'Content-Type': 'application/json' };
const $ = id => document.getElementById(id);
const state = { menu: [], category: 'All', cart: {}, customer: null };
try { state.customer = JSON.parse(localStorage.getItem('lucky_customer') || 'null'); } catch (_) {}
const esc = v => String(v == null ? '' : v).replace(/[&<>]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const money = n => new Intl.NumberFormat('en-IN', { style:'currency', currency:'INR', maximumFractionDigits:0 }).format(Number(n || 0));
async function api(path, options) { const r = await fetch(API + path, Object.assign({}, options || {}, { headers: Object.assign({}, headers, (options && options.headers) || {}) })); const t = await r.text(); let d; try { d = t ? JSON.parse(t) : null; } catch (_) { d = t; } if (!r.ok) throw Error((d && (d.message || d.details || d.hint)) || 'Request failed. Please try again.'); return d; }
function toast(t) { $('toast').textContent = t; $('toast').style.display = 'block'; clearTimeout(toast.timer); toast.timer = setTimeout(() => $('toast').style.display = 'none', 2800); }
function emoji(c,n) { const t=(c+' '+n).toLowerCase(); if(t.includes('boba'))return '🧋';if(t.includes('coffee'))return '🥤';if(t.includes('shake'))return '🥛';if(t.includes('tea'))return '🍵';if(t.includes('fries'))return '🍟';if(t.includes('burger'))return '🍔';if(t.includes('sandwich'))return '🥪';if(t.includes('maggi'))return '🍜';if(t.includes('mojito')||t.includes('mocktail'))return '🍹';if(t.includes('egg'))return '🍳';if(t.includes('petis'))return '🥐';return '🍴'; }
function renderCategories() { const cats=['All'].concat(Array.from(new Set(state.menu.map(x=>x.category).filter(Boolean)))); $('categories').innerHTML=cats.map(c=>'<button class="'+(state.category===c?'active':'')+'" data-cat="'+esc(c)+'">'+(c==='All'?'Everything':esc(c))+'</button>').join(''); $('categories').querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;renderCategories();renderMenu();}); }
function renderMenu() { const q=$('search').value.toLowerCase().trim();const items=state.menu.filter(x=>(state.category==='All'||x.category===state.category)&&(!q||(x.name+' '+x.category+' '+(x.description||'')).toLowerCase().includes(q)));$('products').innerHTML=items.map(x=>'<article class="product"><div class="visual"><span>'+emoji(x.category,x.name)+'</span>'+(x.image_url?'<img src="'+esc(x.image_url)+'" alt="'+esc(x.name)+'" onerror="this.remove()">':'')+'</div><div class="product-body"><h3>'+esc(x.name)+'</h3><p>'+esc(x.description||'Freshly prepared, just for you.')+'</p><div class="product-foot"><span class="price">'+money(x.price)+'</span><button data-add="'+x.id+'" aria-label="Add '+esc(x.name)+'">+</button></div></div></article>').join('');if(!items.length)$('products').innerHTML='<p class="muted">No matches found. Try another search.</p>';$('products').querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{state.cart[b.dataset.add]=(state.cart[b.dataset.add]||0)+1;renderCart();toast('Added to your cart');}); }
function renderCart() { const ids=Object.keys(state.cart).filter(id=>state.cart[id]>0);$('count').textContent=ids.reduce((n,id)=>n+state.cart[id],0);$('cartItems').innerHTML=ids.length?ids.map(id=>{const x=state.menu.find(i=>i.id===id);return '<div class="cart-line"><div><b>'+esc(x.name)+'</b><br>'+money(x.price)+' × '+state.cart[id]+'</div><div class="qty"><button data-q="'+id+'" data-d="-1">−</button>'+state.cart[id]+'<button data-q="'+id+'" data-d="1">+</button></div></div>';}).join(''):'<p class="muted">Your cart is empty. Add a favourite from the menu.</p>';$('cartItems').querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{const id=b.dataset.q;state.cart[id]+=Number(b.dataset.d);if(state.cart[id]<=0)delete state.cart[id];renderCart();});const sub=ids.reduce((n,id)=>n+Number(state.menu.find(x=>x.id===id).price)*state.cart[id],0);$('subtotal').textContent=money(sub);$('total').textContent=money(sub+(sub?40:0));$('checkout').textContent=state.customer?'Place my order ↗':'Sign in to place order ↗';if(state.customer&&state.customer.address&&!$('address').value)$('address').value=state.customer.address; }
function show(id){$(id).hidden=false;}function hide(id){$(id).hidden=true;}
function openAccount(){if(state.customer){$('accountTitle').textContent='Hello, '+(state.customer.name||'there')+'!';$('login').hidden=true;$('loginMessage').textContent='Signed in as '+state.customer.customer_id;}else{$('accountTitle').textContent='Good to see you.';$('login').hidden=false;$('loginMessage').textContent='';}show('account');}
$('login').addEventListener('submit',async e=>{e.preventDefault();$('loginMessage').textContent='Signing in…';try{const d=await api('/rpc/customer_login',{method:'POST',body:JSON.stringify({p_customer_id:$('customerId').value.trim(),p_password:$('password').value})});if(!d||!d.token)throw Error('Sign-in response was incomplete.');state.customer=d;localStorage.setItem('lucky_customer',JSON.stringify(d));$('login').hidden=true;$('accountTitle').textContent='Hello, '+(d.name||'there')+'!';$('loginMessage').textContent='Signed in successfully.';$('accountBtn').textContent=(d.name||'My account').split(' ')[0];renderCart();toast('Welcome back!');}catch(err){$('loginMessage').textContent=err.message;}});
$('checkout').onclick=async()=>{if(!Object.keys(state.cart).length)return toast('Your cart is empty');if(!state.customer){hide('cart');openAccount();$('loginMessage').textContent='Please sign in to place your order.';return;}if(!$('address').value.trim())return toast('Please enter your delivery address');const b=$('checkout');b.disabled=true;b.textContent='Placing order…';try{const items=Object.keys(state.cart).map(id=>({menu_item_id:id,quantity:state.cart[id]}));const d=await api('/rpc/place_customer_cart',{method:'POST',body:JSON.stringify({p_token:state.customer.token,p_items:items,p_address:$('address').value.trim(),p_instructions:$('instructions')?$('instructions').value.trim():'',p_payment_method:$('payment')?$('payment').value:'Cash on Delivery'})});state.cart={};renderCart();hide('cart');openAccount();$('loginMessage').textContent='Order '+(d.order_number||'')+' placed successfully.';toast('Order placed successfully!');}catch(err){toast(err.message);if(/session expired|login again/i.test(err.message)){state.customer=null;localStorage.removeItem('lucky_customer');renderCart();hide('cart');openAccount();}}finally{b.disabled=false;renderCart();}};
$('ordersBtn').onclick=async()=>{if(!state.customer||!state.customer.token){$('orders').textContent='Sign in to view your orders.';return;}const p=$('orders');p.textContent='Loading orders…';try{const d=await api('/rpc/customer_orders',{method:'POST',body:JSON.stringify({p_token:state.customer.token})});const a=Array.isArray(d)?d:(d.orders||d.data||[]);p.innerHTML=a.length?a.map(o=>'<div class="order"><b>Order '+esc(o.order_number||o.id||'')+'</b><span class="status">'+esc(o.status||o.order_status||'Order Placed')+'</span><br>'+money(o.grand_total||o.total||0)+'</div>').join(''):'<p class="muted">No orders to show yet.</p>'; }catch(err){p.textContent=err.message;}};
$('cartBtn').onclick=()=>{renderCart();show('cart');};if($('accountBtn'))$('accountBtn').onclick=openAccount;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>hide(b.dataset.close));$('search').addEventListener('input',renderMenu);
async function init(){try{state.menu=await api('/menu_items?select=id,item_code,name,category,description,price,image_url,preparation_minutes,availability&availability=eq.Available&order=category.asc,name.asc');renderCategories();renderMenu();$('message').textContent=state.menu.length+' menu favourites available.';}catch(err){$('message').textContent='Could not load the menu. Please refresh and try again.';console.error(err);}renderCart();}init();